---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tomcat-deamonset
  labels:
    type: appserver
spec:
  selector:
    matchLabels:
      type: appserver
  template:
    metadata:
      name: tomcat-pod
      labels:
        type: appserver
    spec:
      containers:
        - name: mytomcat
          image: tomee
...
