apiVersion: v1
kind: Service
metadata:
  name: mynginx
  namespace: test-ns
  labels:
    type: proxy
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    type: proxy
    author: intelliqit
