---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    cat: dog
spec:
  containers:
    - name: n1
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8080 
      
... 
