---
apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    type: db
spec:
  containers:
    - name: myredis
      image: redis
      volumeMounts:
        - mountPath: /data/redis
          name: myvolume
  volumes:
    - name: myvolume
      emptyDir: {}
        